cvt_from_str: cvt_from_str.o cxtime.o
	g++ -o $@ cvt_from_str.o cxtime.o
	@echo -n "now running "
	./$@
cvt_to_str: cvt_to_str.o cxtime.o
	g++ -o $@ cvt_to_str.o cxtime.o
	@echo -n "now running "
	./$@
lookup_map: lookup_map.o cxtime.o
	g++ -o $@ lookup_map.o cxtime.o
	@echo -n "now running "
	./$@
